CREATE TABLE ESTUDANTE(
 matricula CHAR(9) PRIMARY KEY,
 nome TEXT,
 data_nasc DATE

);

CREATE TABLE DISCIPLINA(
 codigo INTEGER PRIMARY KEY,
 carga_horaria INTEGER
  
);

CREATE TABLE ESTUDANTEDISCIPLINA(
 matricula CHAR(9),
 disciplina INTEGER,
 periodo_letivo INTEGER

);

ALTER TABLE ESTUDANTEDISCIPLINA ADD CONSTRAINT fgk_matr FOREIGN KEY (matricula) REFERENCES ESTUDANTE (matricula);

ALTER TABLE ESTUDANTEDISCIPLINA ADD CONSTRAINT fgk_disci FOREIGN KEY (disciplina) REFERENCES DISCIPLINA (codigo);

ALTER TABLE ESTUDANTE ALTER COLUMN nome SET NOT NULL;
ALTER TABLE ESTUDANTE ALTER COLUMN data_nasc SET NOT NULL;

ALTER TABLE DISCIPLINA ALTER COLUMN carga_horaria SET NOT NULL;

ALTER TABLE ESTUDANTEDISCIPLINA ALTER COLUMN periodo_letivo SET NOT NULL;
ALTER TABLE ESTUDANTEDISCIPLINA ALTER COLUMN matricula SET NOT NULL;
ALTER TABLE ESTUDANTEDISCIPLINA ALTER COLUMN disciplina SET NOT NULL;



